#!/usr/bin/env bash
set -e

OUTPUT_DIR=${OUTPUT_DIR:-tests/CI/output}

output_dir="--output-dir=${OUTPUT_DIR}"
testsuite_dir="--testsuite-dir=/usr/src/testsuite"
cache_dir="--cache-dir=/usr/src/ci-cache"

init_repo() {
	(
		set -x
		cd /usr/src/$1
		git fetch origin --force
		git checkout -B 16 origin/16
	)
}

init_repo asterisk
init_repo testsuite

set -x
rm -fr ${OUTPUT_DIR} || :
./tests/CI/buildAsterisk.sh ${output_dir} ${cache_dir} "$@"
./tests/CI/installAsterisk.sh
./tests/CI/runUnittests.sh ${output_dir}/unittests

#./tests/CI/runTestsuite.sh ${testsuite_dir} --realtime --initialize-db --cleanup-db
#mv ../testsuite/logs ${OUTPUT_DIR}/testsuite-realtime
#mv ../testsuite/asterisk-test-suite-report.xml ${OUTPUT_DIR}/testsuite-realtime

./tests/CI/runTestsuite.sh ${testsuite_dir}
mv ../testsuite/logs ${OUTPUT_DIR}/testsuite
mv ../testsuite/asterisk-test-suite-report.xml ${OUTPUT_DIR}/testsuite

./tests/CI/processCoverage.sh ${output_dir}
